### ISSUE TITLE
No Method found error on mysql 

### ISSUE THREAD

**Issue by asthajaitly** [yzhanginwa/rails-simple-search#10]
I got the same issue
NoMethodError (undefined method `text?' for #ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::Column:0x007ff45d425c08):

run on ruby:2.1.5 rails: 4.2.0
![screen shot 2016-02-24 at 12 48 14 pm](https://cloud.githubusercontent.com/assets/956293/13278312/aa525802-daf5-11e5-9a4a-d8ce6ff2d89f.png)

**Comment by yzhanginwa** [comment]
Please try the latest version. currently it's 1.1.5.
