### ISSUE TITLE
NoMethodError (undefined method `type_cast' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007ff27025e5d0>):

### ISSUE THREAD

**Issue by xenover** [yzhanginwa/rails-simple-search#11]
Hi

This happens when I try to pass the search a value which' respective column in the database is an integer but I pass a string.

This was changed in Rails 4.2.0 https://github.com/rails/rails/commit/d24e6407a7f5d662cb52ed57efc4d8ee11758170

I'm using rails 4.2.6 and rails-simple-search 0.9.9.

All the best,

xenover

**Comment by yzhanginwa** [comment]
Please try the latest version. It is 1.1.5 currently.
