### ISSUE TITLE
undefined method 'klas' for nil:NilClass Did you mean? class

### ISSUE THREAD

**Issue by Lubmes** [yzhanginwa/rails-simple-search#13]
This is what we get using your gem after making a search.

What could this be?

**Comment by yzhanginwa** [comment]
Hello, thanks for letting me know the issue!

Please let me know which version you're using. Also please paste the full error message here.

**Comment by yzhanginwa** [comment]
In most cases, this issue is caused by using the wrong association name. Please check your code again. I'll close this issue for now. If the problem still persists, please open a new issue and pastes the full error messages here.
