### ISSUE TITLE
bundle update 到 1.1.7 报错

### ISSUE THREAD

**Issue by yammyxing** [yzhanginwa/rails-simple-search#15]
我这边使用的 rails 版本是 4.2.6，ruby 版本是2.3.1，原先使用的rails-simple-search 的版本是 1.1.5，bundle update 到1.1.7之后，search 页面报错：
 
![image](https://user-images.githubusercontent.com/23147304/32360060-748c4bda-c020-11e7-835f-697e468aa130.png)

Gemfile 指定换回1.1.5，页面恢复正常。

**Comment by yzhanginwa** [comment]
The gem has been updated to version 1.1.8. Please give it a try if the issue is still relevant.

**Comment by yzhanginwa** [comment]
If this issue will happen again in the version 1.1.8 or later, I'll look into it.

**Comment by yzhanginwa** [comment]
I examined the code history again. The pagination feature has been removed since v1.1.1. There are many rails pagination gems out there, and they can be used together with rails-simple-search seamlessly.
