### ISSUE TITLE
undefined method `each' for "temp project":String

### ISSUE THREAD

**Issue by laxmanmore** [yzhanginwa/rails-simple-search#6]
Hi,

I have implemented this gem to my project.
I am getting error for controller code "undefined method `each' for "temp project":String".

  def projects_searching
    @search = Search.new(Project, params[:search])
    @projects = @search.run
  end

Thanks,
Laxman More

**Comment by yzhanginwa** [comment]
Sorry that I just noticed your message today. If it's still an issue, please try the new version of 0.9.9.
