### ISSUE TITLE
使用PostGISAdapter，出现一下错误！

### ISSUE THREAD

**Issue by 85636682** [yzhanginwa/rails-simple-search#8]
`undefined method `text?' for #<ActiveRecord::ConnectionAdapters::PostGISAdapter::SpatialColumn:0x007f8527328cd8>`

**Comment by asthajaitly** [comment]
I got the same issue
NoMethodError (undefined method `text?' for #<ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter::Column:0x007ff45d425c08>):

run on ruby:2.1.5  rails: 4.2.0
![screen shot 2016-02-24 at 12 48 14 pm](https://cloud.githubusercontent.com/assets/956293/13278280/59e8aef2-daf5-11e5-8f1f-c032eace7fa6.png)

**Comment by yzhanginwa** [comment]
Sorry that I just noticed your message today. 

The "undefined methes text?" issue should have been resolved. Please use the latest version 1.1.5.
