### ISSUE TITLE
How to Search For has_many :through  Association?

### ISSUE THREAD

**Issue by koochii69** [yzhanginwa/rails-simple-search#9]
e.g i have 3 models User Subject And SubjectUser Model.
User:
has_many :subject_users, dependent: :destroy
has_many :subjects, through: :subject_users, dependent: :destroy

Subject:
has_many :subject_users, dependent: :destroy
has_many :users, through: :subject_users, dependent: :destroy

SubjectUser:
belongs_to :user
belongs_to :subject

how can i search for subjects title?

**Comment by yzhanginwa** [comment]
Sorry that I just noticed your message. I guess you have figured it out yourself.
